version: '3'
services:
  onefs-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-onefs-api
    volumes:
      - ./vlab_onefs_api:/usr/lib/python3.6/site-packages/vlab_onefs_api
    command: ["python3", "app.py"]

  onefs-worker:
    image:
      willnx/vlab-onefs-worker
    volumes:
      - ./vlab_onefs_api:/usr/local/lib/python3.6/dist-packages/vlab_onefs_api/
      - /home/willhn/code/vlab/vlab_inf_common/vlab_inf_common:/usr/local/lib/python3.6/dist-packages/vlab_inf_common
      - /mnt/raid/images/onefs:/images:ro
      - /mnt/tmp:/home
    environment:
      - INF_VCENTER_SERVER=vlab-vcenter.emc.com
      - INF_VCENTER_USER=willhn@vlab.local
      - INF_VCENTER_PASSWORD=li84fe25
      - INF_VCENTER_DATASTORE=generalStorage,generalStorage2,generalStorage3
      - INF_VCENTER_TOP_LVL_DIR=/vlab/users
      - INF_VCENTER_RESORUCE_POOL=generalCompute
      - INF_VCENTER_READONLY_USER=readonly@vlab.local
      - INTERAL_LICENSE_SERVER=changeMe


  onefs-broker:
    image:
      rabbitmq:3.7-alpine
