version: '3'
services:
  onefs-api:
    ports:
      - "5000:5000"
    image:
      willnx/vlab-onefs-api
    environment:
      - VLAB_URL=https://localhost
      - INF_VCENTER_SERVER=virtlab.igs.corp
      - INF_VCENTER_USER=Administrator@vsphere.local
      - INF_VCENTER_PASSWORD=1.Password
    volumes:
      - ./vlab_onefs_api:/usr/lib/python3.6/site-packages/vlab_onefs_api
    command: ["python3", "app.py"]

  onefs-worker:
    image:
      willnx/vlab-onefs-worker
    volumes:
      - ./vlab_onefs_api:/usr/lib/python3.6/site-packages/vlab_onefs_api
      - /mnt/raid/images/onefs:/images:ro
    environment:
      - INF_VCENTER_SERVER=changeME
      - INF_VCENTER_USER=changeME
      - INF_VCENTER_PASSWORD=changeME
      - INF_VCENTER_TOP_LVL_DIR=/vlab

  onefs-broker:
    image:
      rabbitmq:3.7-alpine
